--------------------------------------------------------
--  파일이 생성됨 - 수요일-6월-26-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD_TYPE
--------------------------------------------------------

  CREATE TABLE "KITRI"."BOARD_TYPE" 
   (	"BTYPE" NUMBER, 
	"BTYPE_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "KITRI"."BOARD_TYPE"."BTYPE" IS '게시판형식번호';
 
   COMMENT ON COLUMN "KITRI"."BOARD_TYPE"."BTYPE_NAME" IS '게시판형식이름';
 
   COMMENT ON TABLE "KITRI"."BOARD_TYPE"  IS '게시판형식';
REM INSERTING into KITRI.BOARD_TYPE
SET DEFINE OFF;
Insert into KITRI.BOARD_TYPE (BTYPE,BTYPE_NAME) values (1,'공지사항');
Insert into KITRI.BOARD_TYPE (BTYPE,BTYPE_NAME) values (2,'방명록');
Insert into KITRI.BOARD_TYPE (BTYPE,BTYPE_NAME) values (3,'한줄게시판');
Insert into KITRI.BOARD_TYPE (BTYPE,BTYPE_NAME) values (4,'일반게시판');
Insert into KITRI.BOARD_TYPE (BTYPE,BTYPE_NAME) values (5,'답변게시판');
Insert into KITRI.BOARD_TYPE (BTYPE,BTYPE_NAME) values (6,'앨범게시판');
Insert into KITRI.BOARD_TYPE (BTYPE,BTYPE_NAME) values (7,'자료실');
--------------------------------------------------------
--  DDL for Index PK_BOARD_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "KITRI"."PK_BOARD_TYPE" ON "KITRI"."BOARD_TYPE" ("BTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD_TYPE
--------------------------------------------------------

  ALTER TABLE "KITRI"."BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY ("BTYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "KITRI"."BOARD_TYPE" MODIFY ("BTYPE" NOT NULL ENABLE);
