--------------------------------------------------------
--  파일이 생성됨 - 수요일-6월-26-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD_LIST
--------------------------------------------------------

  CREATE TABLE "KITRI"."BOARD_LIST" 
   (	"BCODE" NUMBER, 
	"BNAME" VARCHAR2(100 BYTE), 
	"BTYPE" NUMBER, 
	"CCODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "KITRI"."BOARD_LIST"."BCODE" IS '게시판번호';
 
   COMMENT ON COLUMN "KITRI"."BOARD_LIST"."BNAME" IS '게시판이름';
 
   COMMENT ON COLUMN "KITRI"."BOARD_LIST"."BTYPE" IS '게시판형식번호';
 
   COMMENT ON COLUMN "KITRI"."BOARD_LIST"."CCODE" IS '카테고리번호';
 
   COMMENT ON TABLE "KITRI"."BOARD_LIST"  IS '게시판리스트';
REM INSERTING into KITRI.BOARD_LIST
SET DEFINE OFF;
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (1,'갤럭시S3 공지사항',1,1);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (2,'갤럭시S3 일반게시판',4,1);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (3,'갤럭시S3 묻고답하기',5,1);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (4,'갤럭시S3 자랑하기',6,1);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (5,'갤럭시S3 자료실',7,1);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (6,'갤럭시NOTE2 공지사항',1,2);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (7,'갤럭시NOTE2 한줄메모',3,2);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (8,'갤럭시NOTE2 일반게시판',4,2);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (9,'갤럭시NOTE2 답변게시판',5,2);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (10,'갤럭시NOTE2 사진자랑',6,2);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (11,'갤럭시NOTE2 자료공유',7,2);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (12,'아이폰5 한줄메모',3,3);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (13,'아이폰5 QNA',5,3);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (14,'아이폰5 폰인증',6,3);
Insert into KITRI.BOARD_LIST (BCODE,BNAME,BTYPE,CCODE) values (15,'아이폰5 앱공유',7,3);
--------------------------------------------------------
--  DDL for Index PK_BOARD_LIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "KITRI"."PK_BOARD_LIST" ON "KITRI"."BOARD_LIST" ("BCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD_LIST
--------------------------------------------------------

  ALTER TABLE "KITRI"."BOARD_LIST" ADD CONSTRAINT "PK_BOARD_LIST" PRIMARY KEY ("BCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "KITRI"."BOARD_LIST" MODIFY ("BCODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOARD_LIST
--------------------------------------------------------

  ALTER TABLE "KITRI"."BOARD_LIST" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_LIST" FOREIGN KEY ("BTYPE")
	  REFERENCES "KITRI"."BOARD_TYPE" ("BTYPE") ENABLE;
 
  ALTER TABLE "KITRI"."BOARD_LIST" ADD CONSTRAINT "FK_CATEGORY_TO_BOARD_LIST" FOREIGN KEY ("CCODE")
	  REFERENCES "KITRI"."CATEGORY" ("CCODE") ENABLE;
